# Generated by Django 5.2.15 on 2026-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Cell number')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Occupied')),
            ],
            options={
                'ordering': ('postamat', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Postamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=50, unique=True, verbose_name='ID of order')),
                ('user_phone', models.CharField(max_length=20, verbose_name='User phone number')),
                ('receive_code', models.CharField(max_length=10, unique=True, verbose_name='Receipt code')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('received', 'Given'), ('failed', 'Placing error')], default='placed', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('placed_at', models.DateTimeField(blank=True, null=True, verbose_name='Placed')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='postamat.cell', verbose_name='Cell')),
                ('postamat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='postamat.postamat', verbose_name='Postamat')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='postamat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='postamat.postamat', verbose_name='Postamat'),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('postamat', 'number')},
        ),
    ]
