# Generated by Django 5.2.15 on 2026-07-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postamat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postamat',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
