# Generated by Django 5.2.15 on 2026-07-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postamat', '0002_alter_postamat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postamat',
            name='is_active',
        ),
    ]
