name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev", "feature/postalbox" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Automatically caches dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SUPERUSER_NICKNAME }}
          SUPERUSER_NAME: ${{ secrets.SUPERUSER_EMAIL }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
        run: |
          python manage.py test postamat/tests/
